pipeline {
  agent any
  
  tools {
    maven 'M2_HOME'
    terraform 'terraform'
  }
  
  environment {
    AWS_ACCESS_KEY_ID = '${Access_Key}'
    AWS_SECRET_ACCESS_KEY = '${Secret_Key}'
  }
  
  stages {
    stage('Package the Application') {
      steps {
        echo "Packaging the Application"
        sh 'mvn clean package'
      }
    }

    stage('Publish Reports using HTML') {
      steps {
        publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: '/var/lib/jenkins/workspace/bank-pro/target/surefire-reports', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: '', useWrapperFileDirectly: true])
      }
    }

    stage('Docker Image Creation') {
      steps {
        sh 'docker build -t kranthi619/insure-me:latest .'
      }
    }

    stage('Docker Login') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'Docker-Hub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
          sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
        }
      }
    }

    stage('Create infrastructure with terraform') {
      steps {
        dir('test-server') {
          sh 'sudo chmod 600 exampl '
          sh 'terraform init'
          sh 'terraform validate'
          sh 'terraform apply --auto-approve'
        }
      }
    }
  }
}

